// packages/react-app/src/topics/essentials/Watchers.tsx
import { useState, useEffect } from 'react'

export default function Watchers() {
  const [question, setQuestion] = useState('')
  const [answer, setAnswer] = useState('Ask a question ending with ?')
  const [searchQuery, setSearchQuery] = useState('')
  const [logs, setLogs] = useState<string[]>([])

  // Equivalent to Vue's watch(question, ...)
  useEffect(() => {
    if (question !== '') {
      setLogs(prev => [...prev, `useEffect [question]: "${question}"`])
    }
    if (question.endsWith('?')) {
      setAnswer('Thinking...')
      const t = setTimeout(() => setAnswer('Yes! 42 is the answer.'), 500)
      return () => clearTimeout(t)
    } else {
      setAnswer('Ask a question ending with ?')
    }
  }, [question])

  // Equivalent to Vue's watchEffect for searchQuery
  useEffect(() => {
    if (searchQuery) {
      setLogs(prev => [...prev, `useEffect [searchQuery]: searching "${searchQuery}"`])
    }
  }, [searchQuery])

  return (
    <div>
      <h2 className="text-lg font-semibold mb-3">Watchers / useEffect</h2>

      <div className="border border-slate-200 rounded-lg p-4 mb-4 space-y-4">
        {/* Question watcher demo */}
        <div>
          <p className="text-sm font-medium text-slate-700 mb-2">Question watcher (useEffect)</p>
          <input
            value={question}
            onChange={e => setQuestion(e.target.value)}
            placeholder="Ask something ending with ?"
            className="border border-slate-300 rounded px-2 py-1 text-sm w-full mb-2"
          />
          <div className="text-sm text-slate-600 bg-slate-50 rounded p-2">
            Answer: <span className="font-medium">{answer}</span>
          </div>
        </div>

        {/* Search useEffect demo */}
        <div>
          <p className="text-sm font-medium text-slate-700 mb-2">Search query (useEffect with [searchQuery])</p>
          <input
            value={searchQuery}
            onChange={e => setSearchQuery(e.target.value)}
            placeholder="Type to trigger useEffect..."
            className="border border-slate-300 rounded px-2 py-1 text-sm w-full"
          />
        </div>

        {/* Log panel */}
        <div>
          <div className="flex items-center justify-between mb-1">
            <p className="text-xs font-medium text-slate-500 uppercase tracking-wide">Effect log</p>
            <button
              onClick={() => setLogs([])}
              className="px-2 py-0.5 bg-slate-200 text-slate-600 rounded text-xs hover:bg-slate-300"
            >
              Clear
            </button>
          </div>
          <div className="bg-slate-900 text-green-400 font-mono text-xs p-3 rounded max-h-40 overflow-y-auto">
            {logs.length === 0 ? (
              <span className="text-slate-500">No effect events yet...</span>
            ) : (
              logs.map((log, i) => <div key={i}>{log}</div>)
            )}
          </div>
        </div>
      </div>

      {/* Explanation */}
      <div className="mt-6 p-4 bg-slate-50 rounded">
        <h3 className="text-sm font-semibold mb-2">Key Differences</h3>
        <ul className="text-sm text-slate-600 space-y-1 list-disc list-inside">
          <li>React has only <code className="bg-white px-1 rounded text-xs">useEffect(fn, deps)</code> — no separate watch vs watchEffect.</li>
          <li>The dependency array <code className="bg-white px-1 rounded text-xs">[question]</code> is like Vue's <code className="bg-white px-1 rounded text-xs">watch(question, ...)</code>.</li>
          <li>An empty <code className="bg-white px-1 rounded text-xs">[]</code> runs once on mount (like <code className="bg-white px-1 rounded text-xs">onMounted</code>).</li>
          <li>Returning a cleanup function from <code className="bg-white px-1 rounded text-xs">useEffect</code> handles teardown (like <code className="bg-white px-1 rounded text-xs">onUnmounted</code>).</li>
          <li>Unlike Vue's <code className="bg-white px-1 rounded text-xs">watchEffect</code>, React doesn't auto-track dependencies — you must list them explicitly.</li>
        </ul>
      </div>
    </div>
  )
}

// packages/vue-app/src/topics/essentials/Watchers.vue
<script setup lang="ts">
import { ref, watch, watchEffect } from 'vue'

const question = ref('')
const answer = ref('Ask a question ending with ?')
const searchQuery = ref('')
const logs = ref<string[]>([])

watch(question, (newVal, oldVal) => {
  logs.value.push(`watch: "${oldVal}" -> "${newVal}"`)
  if (newVal.endsWith('?')) {
    answer.value = 'Thinking...'
    setTimeout(() => {
      answer.value = 'Yes! 42 is the answer.'
    }, 500)
  }
})

watchEffect(() => {
  if (searchQuery.value) {
    logs.value.push(`watchEffect: searching "${searchQuery.value}"`)
  }
})

function clearLogs() {
  logs.value = []
}
</script>

<template>
  <div>
    <h2 class="text-lg font-semibold mb-3">Watchers / useEffect</h2>

    <div class="border border-slate-200 rounded-lg p-4 mb-4 space-y-4">
      <!-- Question watcher demo -->
      <div>
        <p class="text-sm font-medium text-slate-700 mb-2">Question watcher (watch)</p>
        <input
          v-model="question"
          placeholder="Ask something ending with ?"
          class="border border-slate-300 rounded px-2 py-1 text-sm w-full mb-2"
        />
        <div class="text-sm text-slate-600 bg-slate-50 rounded p-2">
          Answer: <span class="font-medium">{{ answer }}</span>
        </div>
      </div>

      <!-- Search watchEffect demo -->
      <div>
        <p class="text-sm font-medium text-slate-700 mb-2">Search query (watchEffect)</p>
        <input
          v-model="searchQuery"
          placeholder="Type to trigger watchEffect..."
          class="border border-slate-300 rounded px-2 py-1 text-sm w-full"
        />
      </div>

      <!-- Log panel -->
      <div>
        <div class="flex items-center justify-between mb-1">
          <p class="text-xs font-medium text-slate-500 uppercase tracking-wide">Watcher log</p>
          <button
            @click="clearLogs"
            class="px-2 py-0.5 bg-slate-200 text-slate-600 rounded text-xs hover:bg-slate-300"
          >
            Clear
          </button>
        </div>
        <div class="bg-slate-900 text-green-400 font-mono text-xs p-3 rounded max-h-40 overflow-y-auto">
          <div v-if="logs.length === 0" class="text-slate-500">No watcher events yet...</div>
          <div v-for="(log, i) in logs" :key="i">{{ log }}</div>
        </div>
      </div>
    </div>

    <!-- Explanation -->
    <div class="mt-6 p-4 bg-slate-50 rounded">
      <h3 class="text-sm font-semibold mb-2">Key Differences</h3>
      <ul class="text-sm text-slate-600 space-y-1 list-disc list-inside">
        <li><code class="bg-white px-1 rounded text-xs">watch(source, callback)</code> explicitly watches a specific ref and provides old/new values.</li>
        <li><code class="bg-white px-1 rounded text-xs">watchEffect(fn)</code> auto-tracks any reactive dependency accessed inside — no need to specify what to watch.</li>
        <li>Vue watchers are synchronous by default (flush: 'pre').</li>
        <li>Both are automatically cleaned up when the component unmounts.</li>
        <li>React has only <code class="bg-white px-1 rounded text-xs">useEffect(fn, deps)</code> — the dependency array <code class="bg-white px-1 rounded text-xs">[dep]</code> is like <code class="bg-white px-1 rounded text-xs">watch(dep, ...)</code>, while no equivalent to <code class="bg-white px-1 rounded text-xs">watchEffect</code> exists (must list deps manually).</li>
      </ul>
    </div>
  </div>
</template>
