// packages/react-app/src/components/TopicRenderer.tsx
import { lazy, Suspense } from 'react'
import { useRouteDispatch } from '../hooks/useRouteDispatch'
import { findTopic } from '@vibe/shared'

const topicModules = import.meta.glob<{ default: React.ComponentType }>('../topics/**/*.tsx')

function toPascalCase(slug: string): string {
  return slug
    .split('-')
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('')
}

export function TopicRenderer() {
  const { category, topicId } = useRouteDispatch()

  if (!category || !topicId) {
    return (
      <div className="text-slate-400 text-sm">
        No topic selected -- navigate to /:category/:topicId
      </div>
    )
  }

  const topic = findTopic(category, topicId)
  const modulePath = `../topics/${category}/${toPascalCase(topicId)}.tsx`
  const moduleLoader = topicModules[modulePath]

  if (!moduleLoader) {
    return (
      <div className="text-slate-400 text-sm">
        Topic component not found: {category}/{topicId}
      </div>
    )
  }

  const TopicComponent = lazy(moduleLoader)

  return (
    <Suspense fallback={<div className="text-slate-400 text-sm">Loading...</div>}>
      <TopicComponent />
    </Suspense>
  )
}

// packages/vue-app/src/components/TopicRenderer.vue
<script setup lang="ts">
import { computed, defineAsyncComponent } from 'vue'
import { findTopic } from '@vibe/shared'

const props = defineProps<{
  category: string
  topicId: string
}>()

const topicModules = import.meta.glob<{ default: any }>('../topics/**/*.vue')

function toPascalCase(slug: string): string {
  return slug
    .split('-')
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('')
}

const topic = computed(() => findTopic(props.category, props.topicId))

const TopicComponent = computed(() => {
  const modulePath = `../topics/${props.category}/${toPascalCase(props.topicId)}.vue`
  const loader = topicModules[modulePath]
  if (!loader) return null
  return defineAsyncComponent(loader)
})
</script>

<template>
  <div v-if="TopicComponent">
    <component :is="TopicComponent" />
  </div>
  <div v-else class="text-sm text-slate-400">
    Topic component not found: {{ category }}/{{ topicId }}
  </div>
</template>
